name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd repository  # Navigate to the directory containing setup.py
        pip install .  # Install the package
    
    - name: Run pytest
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest  # Install pytest
        pytest repository/tests/
